### ISSUE TITLE
Document the package and python modules requirements

### ISSUE THREAD

**Issue by lsandov1** [dlespiau/patchwork#109]
On a clean ubuntu-14.04 OS, installing the required packages for PW, lead to several runtime errors, probably due to python module incompatibility. It would be easier if user can enable a virtual enviroment and use pip install -r <requirements file> to install all requirements, so at least we have a base setup that we know PW can run without trouble. PLUS: The requirements file should be in plain text, it can be fetch easily and store in a file. Some code snippet

```
curl http://patchwork-freedesktop.readthedocs.org/en/latest/reqs.txt > reqs.txt
pip install -r reqs.txt
```

**Comment by lsandov1** [comment]
@dlespiau I just realized that there is this doc http://patchwork-freedesktop.readthedocs.org/en/latest/development.html thus this issue may be irrelevant. Let me go through all the documentation.

**Comment by dlespiau** [comment]
Yup, the requirements.txt files are in https://github.com/dlespiau/patchwork/tree/master/docs. You have to select the right variant, but this should work (those files used by both my CI system (jenkins) and deploy scripts to populate virtual environments.

Please to reopen if you have issues with them.

**Comment by lsandov1** [comment]
It worked, no need to reopen.
