### ISSUE TITLE
Compute the state of a series when one of its patches change state

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#11]
We'd like to have a Series state, to identify which ones need review/work for instance.

**Comment by dlespiau** [comment]
I've started on this and now series do indeed have a status (and a status_summary field with the list/count of the all of states the underlying patches are in). What's missing now is some logic to decide which state the series is in when the patches have different state.

For instance:
- Take a 5 patches series
- 3 patches are "Reviewed"
- 2 patches in "In Review"

--> the Series should be "In Review"

Because the states are fairly generic, we don't really want to add logic that depends on knowing what the states are. Instead we could have a "series weight" associated which each State and the Series would take the higher weight state of the patches. In this example, "In Review" would have a higher weight than "Reviewed".

**Comment by belenbarrospena** [comment]
For series 'in review', we should provide a way of seeing the number of patches reviewed, and the number of patches still in review. I could come up with something if you are interested.

**Comment by dlespiau** [comment]
Of course I'm interested! I was thinking about using http://getbootstrap.com/components/#progress-stacked to show progress with 4 colors: already merged/reviewed/needing-work/un-reviewed

**Comment by belenbarrospena** [comment]
That's definitely an option, although I see 2 problems with the approach:
1. It might take quite a lot of space, which would make it unsuitable for displaying on tables
2. It relies on colour coding, which is not self-evident and will require some kind of legend 

For a similar, but more compacted approach, you could maybe use badges 
http://getbootstrap.com/components/#badges

Or simply table columns. Have 4 columns: Merged | Reviewed | Needing work | Un-reviewed with the number of patches within each category. Some of them will be empty for certain series status, but I don't see that as a major issue.

**Comment by belenbarrospena** [comment]
Question: what are the possible states for a series? For patches, right now there are these states:

action required
new
under review
accepted
rejected
RFC
not applicable
changes requested
awaiting upstream
superseded
deferred

Of the above, which ones apply also to a series? I mean, if in a series of 3 patches 2 were merged and 1 was rejected or was set to awaiting upstream or changes requested, what's the status of the series?

**Comment by belenbarrospena** [comment]
So, we had a little chat, and these is what came out of it.

These are the states we'd like to use for patches:

new [not final]
under review [not final] > automatically when you assigned a reviewer to a series
reviewed [not final]
needs work [not final]
merged [final]
rejected [final]
superseded [final] > automatically when patchwork receives a new series revision

The 'action required' status really equals 'not final', i.e. new or under review or reviewed or needs work

I believe series should have a binary status: either done (i.e. merged, rejected or superseded) or in progress (with the status of the patches themselves providing the reason why it is in progress). @dlespiau would like to implement a weight system where not final states have more weight than final states.

**Comment by dlespiau** [comment]
Time to close that one. There's more work to do on the patch statuses and some automatic transition (eg. set a reviewer -> patch under review, send a r-b tag -> patch reviewed, ...) but that's tracked in other issues.
