### ISSUE TITLE
git-pw support for '--since' parameter

### ISSUE THREAD

**Issue by lsandov1** [dlespiau/patchwork#111]
Currently, git-pw apply and mbox subcommands (and their patches counterpart) support just an ID corresponding to either a series or a patch. Another useful parameter is to query using a 'since' value, for example:

```
# Bring mboxes since Oct 20
git pw mbox --since 2015-10-20
```

This is quite useful in case the maintainer needs to check if recently added patches into PW apply cleanly into master

```
# Test if last patch apply cleanly
git pw mbox --since XXXX-YY-ZZ | git am -3 # or
git pw apply  --since XXXX-YY-ZZ
```

or perhaps some basic testing for finding patch anomalies

   # Test if patch has been signed off
   git pw mbox --since XXXX-YY-XX | checkpatch.py --signed-off
- http://patchwork-freedesktop.readthedocs.org/en/latest/rest.html#get--api-1.0-projects-(string- linkname)-events-

**Comment by dlespiau** [comment]
Same comment as in #112. I don't think query options belong to git pw apply/mbox, just git pw list or git pw poll-events. Closing that one in favour of #115 and #84
