### ISSUE TITLE
git-pw support for '-N' parameter

### ISSUE THREAD

**Issue by lsandov1** [dlespiau/patchwork#112]
Enhancement https://github.com/dlespiau/patchwork/issues/111 is fine but perhaps is to fine-grained for general purposes. We should include a '-N' parameter to indicate to fetch/apply the last N series/patches. Some examples

```
# Test if last series can be apply into the repo
git pw apply -1 # or
git pw mbox -1 | git am -3

# Execute some tests in the last patch and post results  
git pw apply -1 | basic_tests | git pw post-result # or
git pw mbox -1 | git am -3 | basic_tests | git pw post-results
```

Some questions if this parameter is introduced: In case the '--since' parameter is present, should we ignore it?

**Comment by dlespiau** [comment]
What does the 'last N series mean?' last N entries in the events list? last N entries in the list of series ordered by upaded_date?

In the first case, I think it it should be an option of `git poll-events`, in the second case, an option of a new `git pw list` command. See https://github.com/dlespiau/patchwork/issues/115.

In short, I don't like mixing things ie, not a big fan of mixing query options (filtering/ordering/limits) with a command that doesn't have the goal of listing things.

So, for these kind of things, what I would do is:
- First get the list of series you want either with `git pw poll-events` or `git list`
- Apply the list of series retrieved through those commands. For that we need to make `git pw apply` support taking a list of series, which is tracked in https://github.com/dlespiau/patchwork/issues/84 (and you can assign it to yourself if you want to work on that)

So closing that one in favour of the other ones.
