### ISSUE TITLE
git-pw support for '--state' parameter

### ISSUE THREAD

**Issue by lsandov1** [dlespiau/patchwork#114]
Once https://github.com/dlespiau/patchwork/issues/113 is implemented/accepted, it would quite useful (from a mantainer point of view) to fetch/apply those patches/series with a certain result's state, for example

```
# Patch last 10 series with state=success 
git pw apply -10 --state success

# Patch series with failure status so it can be manually analyze and tested since a 
 # specific date
git pw apply --state failure --since 2015-12-7
```

the --state parameter can be multiple, separated by commas for example, but for the moment, lets keep it simple and allow just one state.

**Comment by dlespiau** [comment]
Same comment as in https://github.com/dlespiau/patchwork/issues/112.  I don't think query options belong to git pw apply/mbox, just `git pw list` or `git pw poll-events`. Closing that one in favour of https://github.com/dlespiau/patchwork/issues/115 and https://github.com/dlespiau/patchwork/issues/84
