### ISSUE TITLE
Add a way to parse key-value pairs in patch headers, commit messages or comments

### ISSUE THREAD

**Issue by aphran** [dlespiau/patchwork#130]
The parse_patch function in patchwork/parser.py returns a patch buffer and a comment buffer.

In some cases it might be useful to further parse the comment buffer, to obtain key-value pairs such as:

'From': 'submitter name submitter@ema.il'
'Subject': '[PATCH] something: add x to something

Extended description lines
More description lines'
'Signed-off-by': 'signer name signer@ema.il'
'Upstream-status': 'Pending'

And so on. This information could be useful in several ways, I am not sure if it would be valuable on the UI side of things, but at least people importing the parser module could make use of it.

If you think this is worth doing I may have some code to contribute

**Comment by dlespiau** [comment]
I'm not sure where you're going with this. We already extract the information we want from the mail, including the signed-off-by, tested-by, acked-by tags.

Are you saying you want to refactor this code for another use? mind if I ask what's behind your mind here?

**Comment by dlespiau** [comment]
No update in more than two weeks. Closing. Feel free to re-open it with more information about what you want to do and why.
