### ISSUE TITLE
Add a simple API call to receive submitter details

### ISSUE THREAD

**Issue by ruscur** [dlespiau/patchwork#134]
Submitters are referenced by an ID in the series and patch APIs.  This is used in the views to render their name and email.  Though it can be read from the database or parsed from an mbox, if it's returned in a REST API there should be a place in the API I can look up what it means, rather than just use it in queries.

**Comment by dlespiau** [comment]
Hi,

So there's a non-documented API GET parameter that can be useful to you right now:

http://patchwork.freedesktop.org/api/1.0/projects/intel-gfx/series/?ordering=-last_updated&related=expand

The key is the related=expand. It will "expand" the related fields, ie the primary keys will become a serialization of the object pointed at by that primary key.

I haven't documented this API yet as I'd like to ensure it makes the number of SQL queries still O(1) (ie not depending on the number of series returned). This is true on the series entry point (it even has test coverage!), but not tested for all the "list" entry points.

**Comment by ruscur** [comment]
Yeah, that's useful.  So, leave the issue open until there's a separate API or the field expansion is documented?

**Comment by dlespiau** [comment]
I actually had that exact one captured already. So closing as duplicate. I see you're looking at the API, you may be interested in two scripts using the API that I can share:
- git-pw is a nice example of a few wrapper classes around the API objects (it does use that `expand` parameter to limit the number of HTTP requests needed) : https://github.com/dlespiau/patchwork/blob/master/git-pw/git-pw
- I just pushed an example that should be part of the documentation at some point: how to hook checkpatch.pl to series appearing on the mailing-list, posting test results the users can see (with or without emails with the results on the list): https://github.com/dlespiau/jenkins-patchwork-checkpatch.pl/blob/master/test-checkpatch.py. http://lists.freedesktop.org/archives/intel-gfx/2015-December/083414.html is an example of the resulting email.

If you have any precise-ish question don't hesitate to open issues, the documentation of what's possible definitely needs improvement.

Closed as duplicated of https://github.com/dlespiau/patchwork/issues/68
