### ISSUE TITLE
Some revisions don't have the full list of patches

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#135]
https://patchwork.freedesktop.org/series/2811/

It seems we haven't picked up the full revision (r2 and r3), more investigation needed.

**Comment by charris292** [comment]
Any progress on this issue?  It's blocking the merge of the patch and this patch is being chased by the compute team since it gives a significant performance boost to their workloads.

**Comment by dlespiau** [comment]
It's always possible to resend the full series to trigger the bot instead of relying on accurate parsing (which requires both the developer and patchwork to get things right). It shouldn't block anything.

**Comment by charris292** [comment]
We did try resending, but it still didn't get picked up for testing.  The history of this patch set is:
1.  v1 - this was split into 3 patches: base function, gen8 WA and gen9 WA.  This was successfully tested
2.  v2 - review feedback was to squash the 3 separate patches into 1 patch.  So v2 squashed the 3 patches into 1.  This was successfully reviewed, but wasn't picked up for testing.
3.  v3 - we assumed that v2 had been unlucky and had hit a glitch in the BAT system.  So we resent a v3 to try to kick the system into life, but it didn't work.

Do we need to change the patch subject to get patchwork to send it for testing?

Is there any way to manually get patchwork to send it for testing?

**Comment by dlespiau** [comment]
Right, so it's definitely a bug in patchwork, I'll have a look at it next.

Meanwhile, changing the subject will start a new series, so you can get testing. In case you haven't seen it already, I started documenting what should be understood:

http://patchwork-freedesktop.readthedocs.org/en/latest/manual.html#submitting-patches

**Comment by dlespiau** [comment]
So I thought I had fixed this by reworking how the number of patches in series revision is stored a few days ago. I did double check with some more testing coverage and it seems to be fixed indeed.

That fix is from the 26th, so series before then are buggy and won't trigger the CI system. New revisions sent now should work though.

In case you're interested: https://github.com/dlespiau/patchwork/commit/f2873690eda465c069ac986254556ea1f7eb7c60

I think that's fixed, please to reopen if the problem still occurs.
