### ISSUE TITLE
Allow filtering series by test result with the REST API

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#138]
For both the web UI and git-pw, we'd like to filter series by their test results.

**Comment by belenbarrospena** [comment]
You probably know already, but UI design for this is in place. See 
http://belenbarrospena.github.io/patchwork-redesign/

and pages 18 to 20 of 
https://github.com/belenbarrospena/patchwork-redesign/blob/gh-pages/design_documentation/Filters.pdf

**Comment by dlespiau** [comment]
This is now done!
