### ISSUE TITLE
Don't show the selection checkbox on lists if the user is not allowed to modify the series/patch

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#142]
Currently, one needs to be a project maintainer to assign reviewers (I'd like to extend the roles in the project, but that's an orthogonal discussion).

Current, when not allowed to set a reviewer (ie not a maintainer), the operation fails without any feedback to the user.

**Comment by belenbarrospena** [comment]
Options you cannot use should not be shown to you: that's just teasing ;)

So, we don't need an error message: we need error prevention. If you are not a maintainer, the 'Set reviewer' action should not display when you select one or more series. I hope this makes sense.

**Comment by dlespiau** [comment]
ah yes! I had forgotten about this, will change what the issue is really about then.
