### ISSUE TITLE
Have a way to unset the reviewer

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#143]
If a reviewer is already set on a series, we can set a new reviewer, but we can't unset it, ie. going back to no reviewer.

The filters have two ways to be cleared, the cross and a link next to the apply button. I think the link idiom could be reused for the Actions (ie what is available in the toolbar when one or more series are selected) and be what allows to implement "unset reviewer".

**Comment by belenbarrospena** [comment]
I would use something different, mainly to be unequivocal about what 'unset reviewer' does: it's not going to clear your selections in the 'set reviewer' dialog and revert it to its default state, as the 'clear filter' option does. It's going to change the properties of the selected series, like any of the other options provided by the 'set reviewer' dialog. So I would make it look like them. 

We can just add a third radio button with label "Set reviewer to 'None'" so there is no doubt as to what's going to happen if you select that option :) 

You can see  how it would look like here

http://belenbarrospena.github.io/patchwork-redesign/index.html
