### ISSUE TITLE
Test option to send result emails on error only

### ISSUE THREAD

**Issue by ruscur** [dlespiau/patchwork#147]
By default, Patchwork will send an email to the mailing list if a test result is published with "warning" or "failure" status (I think).  It'd be nice to be able to configure this per-project, so a maintainer can opt-out of having Patchwork post to the mailing list, or only if it's more serious than a warning.  That way, the benefit of having test results posted on the series page in Patchwork is still there without having to disturb the list.

**Comment by dlespiau** [comment]
Hi,

FWIW, I've promised other people interested in tests to have proper documentation for testing integration in patchwork written this week. I can at least show you a picture of the intended flow as a teaser:

  http://entropy.lespiau.name/patchwork/testing-ci-flow.png

By default, patchwork will not send any email, that's to allow test scripts authors to debug/develop without the risk of sending confusing emails to the ml.

The test result emailing is actually fine-grained, configurable per test identified by a unique tuple (project, test-name). See the unique_together = [('project', 'name')] Meta field of the Test model (patchwork/models.py). That configuration is already quite flexible:
- send to ml, patch submitter, a list of email addresses or no email at all
- if sending an email: always send it or send the email on warning/failure as you said

So the only bit missing for you is to be able to configure the mailing out only error, fair enough, should be straightforward.

**Comment by dlespiau** [comment]
Oh actually, you don't mention error only, so the current behaviour should fit what you wanted (which seems to be a natural desirable behaviour indeed)

**Comment by ruscur** [comment]
Only error would be nice to have, I think.

I've been working on a (separate) tool to do the bridging between Patchwork and test systems (so, polling Patchwork until there's a new series, applying it, pushing it to a remote, calling out to a CI server to run tests, polling until they're done, pushing results back to Patchwork) - hopefully I'll have something to show soon.

**Comment by dlespiau** [comment]
Exciting news!

I'll keep the bug opened until we have the "error only" option as well then.

I'm definitely interested in more feedback on the API/features as you've been doing, there's definitely room for improvement a bit everywhere. For instance, that's the current state of my thinking to try and avoid polling: https://github.com/dlespiau/patchwork/issues/148

**Comment by dlespiau** [comment]
I don't remember if I gave you those links already, but just in case if you're interested to know more about what we're up to:

http://damien.lespiau.name/2016/02/augmenting-mailing-lists-with-patchwork.html

and more documentation about the testing flow:

http://patchwork-freedesktop.readthedocs.org/en/latest/testing.html

**Comment by dlespiau** [comment]
And that's now done in e44ec1dc2470fbe5e0f9bd4451220019a0120bc2
