### ISSUE TITLE
Ack.*-by

### ISSUE THREAD

**Issue by djdeath** [dlespiau/patchwork#156]
Could it be possible to have "Acknowledged-by" also covered by "Ack-by"?

**Comment by dlespiau** [comment]
Let's say no :) and ask people to do it "properly", the tag is called Acked-by.

https://github.com/torvalds/linux/blob/master/Documentation/SubmittingPatches#L505

**Comment by belenbarrospena** [comment]
I know this is closed, but fwiw, I agree with the submitter. Mr Torvalds can set as many rules as he wants, but people will still do as they please (thankfully). Interpreting "Acknowledged-by" and "Ack-by" as meaning "Acked-by" doesn't seem hard to do, and would make Patchwork a bit more forgiving.

**Comment by djdeath** [comment]
Numbers might be against us :(

```
$ git log | grep Acked-by | wc -l
80824
$ git log | grep Ack-by | wc -l
10
$ git log | grep Acknowledged-by | wc -l
1
```

**Comment by djdeath** [comment]
We definitely need a \o/-by at some point though ;)
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=8b47047bd103c9fdb50440790a2ef17fa69a35c4

**Comment by belenbarrospena** [comment]
Well, I care about those 11 people :)
