### ISSUE TITLE
Restrict patches to git send-email mails

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#16]
Right now we have a number of false positive: when people send a diff in the middle of their email, we treat it as a patch. We should have a per-project option to only consider git send-email mails.

**Comment by stephenfin** [comment]
Be careful with how you do this - `git-send-email` in the MessageID is not a very good heuristic as the MessageID can be easily configured/overriden (I see this done rather often in some OSS mailing list archives). You could probably try parsing mbox files using some form of Git Python bindings (i.e. `git-python`) but this would be expensive.

**Comment by dlespiau** [comment]
There's the X-Mailer header that seems to be the right thing to look at:

X-Mailer: git-send-email 1.8.3.1

**Comment by stephenfin** [comment]
Ah yes - just be aware that that isn't present if you download the archives (which is what I've been working with).

**Comment by dlespiau** [comment]
Ah, that's because mailman does all sorts of weird stuff to the mails. Probably better to use proper emails.

**Comment by dlespiau** [comment]
Now implemented (with test cases!)
