### ISSUE TITLE
Non relevant series remain in the series view

### ISSUE THREAD

**Issue by zecke** [dlespiau/patchwork#165]
For a patch it is possible to "Accept" / "Reject" / "Supersede" and then the patch disappears from the patch listview. The same does not seem to be possible for the Series view.
- A review request made on a series is sticky. Rejecting the patch (one revision, one patch) does not help. Commenting by mail doesn't help either, etc...
- Series never vanish. To track work that still needs to be done, series should disappear just like it is possible with patches.

**Comment by dlespiau** [comment]
You just have discovered the next big thing I need to do. Series need to have a status derived from its underlying patches and that status can be used to not display series that are "done".

I did spend some time this week looking at this and have a start, There's quite a bit of work around patch and series status in general (for instance, when giving a r-b tag, the patch status doesn't change to 'reviewed' currently). I have been shying away from this work a bit too long now, I'll have a good look asap.

**Comment by zecke** [comment]
Thank you for the quick response. I have installed it at https://patchwork.osmocom.org for our GSM/3G and I look forward to make good use of it. I am already committed to too much so I will just cheer for you. Thanks for moving patchwork forward!

**Comment by dlespiau** [comment]
Ok, series now have a state and series that are 'Done' aren't shown up in the series list by default nor in the list reviews. The filter toolbar has also a new filter to display series with a specific status(es).

This is deployed on fdo if you want a peek: https://patchwork.freedesktop.org/project/intel-gfx/series

Next steps for this work is more automatic patch status changes (ie, a r-b tag should change the patch status to reviewed), but these new features are tracked in separate issues. Closing then.

**Comment by zecke** [comment]
thanks. I rebased and used ./manage.py syncdb. Status of series shows as "undefined". What other migration step do I need?

http://patchwork.osmocom.org/project/gprs/series/?ordering=-last_updated

**Comment by dlespiau** [comment]
I think you're missing the collect static setp to update the .js files (patchwork.js, series-list.js, ...) 

I guess I can give you what I roughly do for fdo: I use fabric (http://www.fabfile.org/) with something close to what I put below. A few remarks:
- with the file below, a simple `$ fab deploy` is enough to deploy patchwork on freedesktop.org.
- I use quilt to manage a pile patch on top of master (mainly configuration and a few hacks), hence the git quiltimport.
- the most interesting part for you is probably patchwork_migrate(), these are really the steps to migrate patchwork
- the supervisord stuff is to maintain a pool of background celery workers (currently used to send emails to people set as reviewer so they are aware of it). I still need to write that part of the documentation but that work is captured elsewhere.

fabfile.py:

```
from __future__ import with_statement
from fabric.api import local, run, hosts, env, cd, prefix, task, execute
from contextlib import contextmanager

fdo_patchwork = 'damien@emeril.freedesktop.org'
fdo_root      = 'damienR@emeril.freedesktop.org'

env.use_ssh_config = True

@task
def patchwork_update_tree():
    local("git checkout freedesktop.org")
    local("git branch -D freedesktop.org-deploy || true")
    local("git checkout -b freedesktop.org-deploy freedesktop.org")
    local("git quiltimport")
    local("git push fdo -f freedesktop.org-deploy:next")
    local("git checkout freedesktop.org")
    local("git branch -D freedesktop.org-deploy")


# Patchwork context: Work in patchwork's checkout directory and with its
# virtualenv activated
@contextmanager
def patchwork():
    with cd('/srv/patchwork.freedesktop.org/'):
        with prefix('source .virtualenvs/django-1.8/bin/activate'):
            yield


@task
@hosts(fdo_patchwork)
def patchwork_migrate():
    with patchwork():
        run("git checkout freedesktop.org")
        run("git reset --hard next")
        run("git branch -d next")
        run("pip install --upgrade -r docs/requirements-prod-fdo.txt")
        run("./manage.py collectstatic --noinput")
        run("./manage.py loaddata default_states")
        run("./manage.py loaddata default_tags")
        run("./manage.py loaddata default_events")
        run("./manage.py migrate")


@task
@hosts(fdo_root)
def supervisor_reload():
    run('supervisorctl reread')
    run('supervisorctl restart all')


@task
@hosts(fdo_root)
def apache_restart():
    run('apache2ctl configtest')
    run('/etc/init.d/apache2 restart')


@task
def deploy():
    execute(patchwork_update_tree)
    execute(patchwork_migrate)
    execute(supervisor_reload)
    execute(apache_restart)
```
