### ISSUE TITLE
Series page calls API with "[object%20Object]" project ID

### ISSUE THREAD

**Issue by ruscur** [dlespiau/patchwork#173]
`[31/Mar/2016 11:17:18] "GET /api/1.0/projects/[object%20Object]/series/?related=expand&ordering=-last_updated&page=1&perpage=100&offset=0 HTTP/1.0" 200 59

I updated to the latest source from my instance that was about a month old (which sadly I didn't note the commit of), ran migrations.  The patch data is fine, the series API is fine, but the series page is busted since it incorrectly calls the API with that "[object%20Object]" blob.

Any ideas what could cause this?  If not, I'll try and bisect.

**Comment by dlespiau** [comment]
Would it be, by any chance, that you're still serving the old javascript files (ie old patchwork.js, but new base.html template). I describe the way I do migration in https://github.com/dlespiau/patchwork/issues/165 and there's a 'collectstatic' step in there that will collect all static files into the directory served by the HTTP server.

Another thing that happened to me is that, by default, we keep serving "patchwork.js", the browser will cache the file and not download a newer version automatically (unless you force a full reload with ctrl+r). The way I  solved that is to use STATICFILE_STORAGE: 

https://github.com/dlespiau/patchwork/blob/master/patchwork/settings/production.example.py#L62
https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#manifeststaticfilesstorage

If you look at patchwork.freedesktop.org sources, I now serve "/static/js/patchwork.dcf6e8bfecd4.js". The hash of the content of the file is appended to the file name, so different version of the file will have different names and thus always up to do date.

**Comment by ruscur** [comment]
Running a `collectstatic` fixed it, cheers.

**Comment by dlespiau** [comment]
Out of curiosity, are you managing a public patchwork instance?

For the general problem of "where was my branch at again?" you should read on git reflog :) https://git-scm.com/docs/git-reflog

**Comment by ruscur** [comment]
I'm not managing one that anyone other than me uses.  I work with @jk-ozlabs and I'm writing stuff that uses the API, and thus working on convincing him to eventually move patchwork.ozlabs.org to this version.

Thanks for putting me onto `git reflog`, I feel like I learn something new about git every day :)

**Comment by dlespiau** [comment]
Oh my, we may find a way to reconcile the two branches, but given that: series support is taking a different way, the REST API is taking a different way and the check/test result code is different, that sounds hard :/

**Comment by stephenfin** [comment]
My two cents: I don't imagine it would be too difficult to rectify the branches, and this should probably be a goal. The series work on fdo is very similar to what's proposed upstream, though the upstream variant adds full-fledged cover letter support and the ability to track deep-threaded series. The REST API should be functionally identical, though it will be optional upstream per the constraints of some users of patchwork. The check API is likely the biggest barrier, and while I understand the constraints that the fdo community is under RE: test run time, I still disagree with not enforcing bisectability through testing every patch individually. This could be likely be rectified by moving fdo's TestResult code into a Django application, similar to how Linaro added stats to their instance. Thoughts?

**Comment by dlespiau** [comment]
It's probably not a good idea to discuss this here, in a totally orthogonal and closed bug. Mailing-list would be better. Just a correction, this branch can, of course, test each patch individually. The combinations it supports:
- Test one series a a whole, send the test result back on the series
- Test each patch of a series, send only 1, consolidated, result back on the series
- Test each patch (of a series or not) and send the test result back on the patch
