### ISSUE TITLE
Can't change patch properties

### ISSUE THREAD

**Issue by avagin** [dlespiau/patchwork#182]
When I try to change a patch status, I always get the same error:

```
DoesNotExist at /patch/20/
Event matching query does not exist.
```

http://dpaste.com/0VTAPXZ

**Comment by ruscur** [comment]
(should be) fixed by the following:

`python manage.py loaddata default_events`

**Comment by avagin** [comment]
@ruscur Where can I find this patch? I would like to test it. Thanks.

**Comment by avagin** [comment]
Now it works. Thanks.
