### ISSUE TITLE
Show cover letter message/body in series created with pull request

### ISSUE THREAD

**Issue by joselamego** [dlespiau/patchwork#190]
The usual cover letter message is not displayed in series Details [example: 1] when a new series is created from patches submitted through pull request [example 2]. The message should be included the same as when git send email is used.

[1] https://patchwork.openembedded.org/patch/126781/
[2] http://lists.openembedded.org/pipermail/openembedded-core/2016-July/123696.html

Corresponding Yocto issue: https://bugzilla.yoctoproject.org/show_bug.cgi?id=9904

**Comment by dlespiau** [comment]
Have you started on this? I unfortunately won't have the time to look into this before a long while.

**Comment by joselamego** [comment]
I'm currently working on issue #61, but will start working on this as soon as I can.
