### ISSUE TITLE
Can't seem to query the test results from the REST API

### ISSUE THREAD

**Issue by mupuf** [dlespiau/patchwork#204]
Hey,

I am trying to read the test results (and when they were last updated) of a certain revision of a patch series.

By browsing the code[1], I found that the format should be the following, but this does not seem to work:
https://patchwork.freedesktop.org/api/1.0/series/28370/revisions/1/test-results/

Am I doing something wrong?
Cheers

[1] https://github.com/dlespiau/patchwork/blob/d8a74c393d77125bfd308e491be9a82b6b6f27d0/patchwork/urls.py#L62

**Comment by ivyl** [comment]
As you can see in the HTML API preview / doc you've linked, it only allows POST and OPTIONS verbs, 
so 405 on GET is expected.

Implementation details:
https://github.com/dlespiau/patchwork/blob/d8a74c393d77125bfd308e491be9a82b6b6f27d0/patchwork/views/api.py#L565

**Comment by ivyl** [comment]
fixed with 1cb2039c554de3f552cae4bc8b0d83449e29d364
(already deployed on  freedesktop)
