### ISSUE TITLE
Patch identification gone wrong in a top-posted reply

### ISSUE THREAD

**Issue by jnikula** [dlespiau/patchwork#39]
Reply to a patch resulted in a new patchwork entry
http://patchwork.freedesktop.org/patch/61671/
instead of a comment in
http://patchwork.freedesktop.org/patch/61643/

A patch from Gavin stood out a bit. :)

**Comment by dlespiau** [comment]
I've deployed the "only consider git send-email emails as potential patches" option on fdo, and configured the intel-gfx to use it. That should remove the false positives (this is not the only one) we've had with random diff hunks in emails.
