### ISSUE TITLE
Add <nobr> or equivalent on date

### ISSUE THREAD

**Issue by imirkin** [dlespiau/patchwork#44]
On a 1200-wide screen in chromium 45, the dates get wrapped, making each row be 2 lines long. Sticking a <nobr> around the date (or white-space:nowrap probably would work too) on the td's that contain the dates fixes it. Some long names/etc still wrap, but that's expected.

**Comment by dlespiau** [comment]
Sorry it took so long to fix this (my excuse is that I was doing some heavy lifting with patch parsing) but the fix is now be deployed on fdo.
