### ISSUE TITLE
Add a 'since' GET parameter to /api/1.0/projects/$name/events/

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#48]
To make the life of clients easier we should support filtering the events since the last time the client has polled.

A way to do that is to add a 'since' GET parameter, the client can specify the last event_time string there and it should do the trick.
### References
- http://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend
- https://django-filter.readthedocs.org/en/latest/

**Comment by dmgciubotaru** [comment]
Changes commited https://github.com/dmgciubotaru/patchwork/commit/f48bcf12a179356ec982b5c7e6492b3768f76f6d

Docs 
https://github.com/dmgciubotaru/patchwork/commit/00d45ce7df1cc1e1f37e6eff83d7b68e0a73811f

Another test for this feature 
https://github.com/dmgciubotaru/patchwork/commit/1f86d8235a684e54337730e7906a18a4fc94a3ce

**Comment by dmgciubotaru** [comment]
FIX: Event API fails if no 'since' provided
https://github.com/dmgciubotaru/patchwork/commit/23d63ef14b0e93751c508b5cb423d9ac26a7fecb

**Comment by dlespiau** [comment]
Merged and deployed.
