### ISSUE TITLE
Provide an easy way to set up patchwork for development

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#53]
It can be a bit daunting to look at the patchwork installation documentation (which needs a full overhaul see issue #52). We ought to be able to do:

```
$ git clone https://github.com/dlespiau/patchwork/
$ ./scripts/setup-devel
$ ./manage.py runserver
```

and be ready to develop, at least for simple modifications. That would mean:
- check if virtualenv is installed and set it up
- have a default configuration using sqlite
- preload a few test projects and test patches

**Comment by dmgciubotaru** [comment]
Script commited 
https://github.com/dmgciubotaru/patchwork/commit/d2080bfb494edcd67b2c2ff9722bd1bf0e44391a

**Comment by dlespiau** [comment]
Alright, merged! thanks, it's quite nice :)
