### ISSUE TITLE
Allow download of mbox for a revision of a series

### ISSUE THREAD

**Issue by imirkin** [dlespiau/patchwork#76]
Would be great to be able to click a button and download the mbox for a particular revision of a series. Something that I could feed into 'git am'.

**Comment by dlespiau** [comment]
It would! wouldn't it? :)

Maybe you could try git-pw!

http://patchwork-freedesktop.readthedocs.org/en/latest/manual.html#git-pw

Or the API entry point directly:

curl -s http://patchwork.example.com/api/1.0/series/42/revisions/2/mbox/ | git am -3

http://patchwork-freedesktop.readthedocs.org/en/latest/rest.html#get--api-1.0-series-(int- series_id)-revisions-(int- version)-mbox-

(yes, a mail about patchwork status on freedesktop.org is overdue)

**Comment by imirkin** [comment]
Neat-o. A link to that bla/api/morebla/mbox/ link in the Rev tab (on the tab itself or inside the tab contents) would be fantastic. If there's an easy way to access the fd.o database (for sample data), happy to hack on it myself.

**Comment by dlespiau** [comment]
There isn't an easy access to that db, buuuut, we have an quick on boarding option from Gabriel that isn't merged yet, but I just tested it and it's working on 2 different machines now.

https://github.com/dlespiau/patchwork/tree/20151106-onboarding

https://github.com/dlespiau/patchwork/blob/20151106-onboarding/docs/development.rst#quick-start

**Comment by dlespiau** [comment]
Btw, it's not so obvious, to get the right API URL you can use, in a template:

```
{% url 'seriesrevision-mbox' series.pk revision.version %}
```

and the template you want: patchwork/templates/patchwork/series.html
