### ISSUE TITLE
Allow 'bulk tools' to manage your own patches

### ISSUE THREAD

**Issue by evelikov** [dlespiau/patchwork#82]
Currently if you have multiple patches that are in the wrong state you have to fix them one by one.

One workaround is to give the person admin rights, which may or may not be desired.

The second option is to allow extra widgets/tools when one has filtered the patches by authored by them (might even add a "self"/"me" field in the dropdown ?)

**Comment by dlespiau** [comment]
Huuum, https://github.com/dlespiau/patchwork/commit/a785656e3e2401a8611d7b041d3f89456d8f37ce should make it work at least  (it's deployed on fdo). Have you tried recently? (I haven't).

**Comment by dlespiau** [comment]
I just tried on a project where I don't have the maintainer role and I could update in bulk the state of my  'New' patches: filtered the patches by my name as submitter, selected all, updated the state to superseded.

So seems to work for me. Closing. Do reopen if I didn't understand what you were meaning.

**Comment by evelikov** [comment]
Indeed it works like a charm.
