### ISSUE TITLE
Make series id appear in the list of series 

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/patchwork#86]

**Comment by belenbarrospena** [comment]
Two questions about this:
1. Can you paste an example of a series ID? Are they similar to patch IDs? Something like: 1448357676-27837-2-git-send-email-maarten.lankhorst@linux.intel.com
2. Why do you want to see the series id in this context (the context being the list of series)?

Thanks!

**Comment by dlespiau** [comment]
1. The series id is the series number, just like a bugzilla number. It's used to uniquely identify the series. It can be used by git pw to apply the series in one go for instance.
2. to be able to refer to the series, just like a bugzilla bug #

**Comment by belenbarrospena** [comment]
got it. Thanks!

**Comment by dlespiau** [comment]
Oh, that's done now!
